In [ ]:
import sklearn
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
BASE_URL = "drive/MyDrive/Citadel Women's Datathon/code"

In [ ]:
tax_returns_median_df = pd.read_csv(f"{BASE_URL}/tax_returns_median.csv")
tax_returns_median_df.head()

   Unnamed: 0  ZIPCODE  MEDIAN_INCOME
0           0    35004              3
1           1    35005              3
2           2    35006              3
3           3    35007              3
4           4    35010              3

In [ ]:
del tax_returns_median_df[tax_returns_median_df.columns[0]]

In [ ]:
tax_returns_median_df.head()

   ZIPCODE  MEDIAN_INCOME
0    35004              3
1    35005              3
2    35006              3
3    35007              3
4    35010              3

In [ ]:
mental_health_df = pd.read_csv(f"{BASE_URL}/at_risk_percents.csv")

In [ ]:
mental_health_df.head()

     At Risk  Year       State
0  25.344107  2020  California
1  41.866438  2020   Wisconsin
2  23.664122  2020     Wyoming
3  29.388213  2020       Texas
4  40.058055  2020      Hawaii

In [ ]:
us_state_to_abbrev = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
    "District of Columbia": "DC",
    "American Samoa": "AS",
    "Guam": "GU",
    "Northern Mariana Islands": "MP",
    "Puerto Rico": "PR",
    "United States Minor Outlying Islands": "UM",
    "U.S. Virgin Islands": "VI",
}

In [ ]:
zip_to_cd_df = pd.read_csv(f"{BASE_URL}/zip_to_cd.csv")

In [ ]:
zip_to_cd_df.head()

   state_fips state_abbr    zip  cd
0           1         AL  31905   3
1           1         AL  35004   3
2           1         AL  35005   6
3           1         AL  35005   7
4           1         AL  35006   4

In [ ]:
tax_returns_median_df.tail()

       ZIPCODE  MEDIAN_INCOME
27638    83122              3
27639    83126              4
27640    83127              4
27641    83128              4
27642    83414              5

In [ ]:
swapped_us_state_to_abbrev = {}
for key in us_state_to_abbrev:
  val = us_state_to_abbrev[key]
  swapped_us_state_to_abbrev[val] = key

In [ ]:
zip_to_cd_df.tail()

       state_fips state_abbr  zip  cd
46099          78         VI  802   0
46100          78         VI  820   0
46101          78         VI  830   0
46102          78         VI  840   0
46103          78         VI  850   0

In [ ]:
def get_state_for_zip(zipcode):
  temp = zip_to_cd_df[zip_to_cd_df["zip"] == zipcode]
  state = temp.iloc[0]["state_abbr"]
  return swapped_us_state_to_abbrev[state]

In [ ]:
mh_output_df = {"ZIPCODE": [], "MEDIAN_INCOME": [], "AT_RISK": []}
mental_health_df = mental_health_df[mental_health_df["Year"] == "2020"]
mental_health_df.head()

     At Risk  Year       State
0  25.344107  2020  California
1  41.866438  2020   Wisconsin
2  23.664122  2020     Wyoming
3  29.388213  2020       Texas
4  40.058055  2020      Hawaii

In [ ]:
mental_health_df.head()

     At Risk  Year       State
0  25.344107  2020  California
1  41.866438  2020   Wisconsin
2  23.664122  2020     Wyoming
3  29.388213  2020       Texas
4  40.058055  2020      Hawaii

In [ ]:
for row in tax_returns_median_df.iterrows():
  try:
    zipcode = row[1]["ZIPCODE"]
    med_income = row[1]["MEDIAN_INCOME"]
    state = get_state_for_zip(zipcode)
    temp = mental_health_df[mental_health_df["State"] == state]
    mh_at_risk = temp.iloc[0]["At Risk"]
    
    mh_output_df["ZIPCODE"].append(zipcode)
    mh_output_df["MEDIAN_INCOME"].append(med_income)
    mh_output_df["AT_RISK"].append(mh_at_risk)
  except:
    continue

In [ ]:
output = pd.DataFrame.from_dict(mh_output_df)

In [ ]:
output.to_csv(f"{BASE_URL}/mh_output.csv")